name: Luca Di Sera
# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
  
permalink: /blog/:year/:month/:day/:title

paginate: 5
paginate_path: "/page:num/"

excerpt_separator: <!--godomalissimo-->

plugins:
  - jekyll-sitemap

theme: jekyll-theme-hacker
