name: Luca Di Sera
markdown: kramdown

highlighter: rouge

permalink: /blog/:year/:month/:day/:title

paginate: 5
paginate_path: "/page:num/"

excerpt_separator: <!--godomalissimo-->

plugins:
  - jekyll-sitemap

theme: jekyll-theme-hacker
